---
- name: Overwrite original driver with hard link to patched version
  listen: nvidia_driver_patched
  become: true
  ansible.builtin.file:
    src: /opt/nvidia_driver.custom.run
    dest: /opt/nvidia_driver.run
    mode: "0755"
    state: hard
  tags:
    - nvidia
- name: Remove the tmp file
  listen: nvidia_driver_patched
  become: true
  ansible.builtin.file:
    path: /opt/nvidia_driver.custom.run
    state: absent
  tags:
    - nvidia
