---
proxmox_no_nag_apply: false
proxmox_no_nag_confirmation: ""
proxmox_no_nag_confirmation_value: apply-proxmox-no-nag
proxmox_no_nag_debian_suite: trixie
proxmox_no_nag_repository_url: http://download.proxmox.com/debian/pve
proxmox_no_nag_keyring: /usr/share/keyrings/proxmox-archive-keyring.gpg
