---
- name: Remove Proxmox resources
  hosts: all
  vars_files:
  - vars.yml
  tasks:
    - name: Remove Proxmox VM
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_api_host }}"
        api_user: "{{ proxmox_api_user }}"
        api_token_id: "{{ proxmox_api_id }}"
        api_token_secret: "{{ proxmox_api_secret }}"
        vmid: "{{ proxmox_vm_id }}"
        state: absent
