---
- name: test
  hosts: all
  gather_facts: false
  vars_files:
  - vars.yml
  tasks:
  - name: Create VM
    community.general.proxmox_kvm:
      api_host: "{{ proxmox_api_host }}"
      api_user: "{{ proxmox_api_user }}"
      api_token_id: "{{ proxmox_api_id }}"
      api_token_secret: "{{ proxmox_api_secret }}"
      node: "{{ proxmox_vm_node }}"
  
      # Basic VM info
      vmid: "{{ proxmox_vm_id }}"
      name: "{{ proxmox_vm_name }}"
      ostype: l26
      #bios: ovmf
      
      # Hardware info
      cores: 1
      memory: 512
      scsihw: virtio-scsi-pci
      scsi: {"scsi1":"local:cloudinit,format=qcow2"}
      #efidisk0: {"storage":"local-lvm:0","pre_enrolled_keys":"0"}
      #virtio: {"virtio0":"local-lvm:vm-{{ proxmox_vm_id }}-disk-1,discard=on"}
      serial: {"serial0":"socket"}
      vga: serial0
      boot: order=scsi1
      
      # Storage and network info
      net: {"net0": "virtio,bridge=vmbr0"}
      ipconfig: {"ipconfig0": "ip=dhcp"}
      #nameservers: null
      
      # Cloud-init info
      ciuser: sysadmin
      cipassword: $(openssl passwd -6 $CLEARTEXT_PASSWORD)
      sshkeys: "{{ proxmox_vm_ssh_key }}"
      #sshkeys: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
  
      # Desired state
      state: present
