---
- name: Include variables based on distribution
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "dist_{{ ansible_distribution }}.yaml"
        - "os_{{ ansible_os_family }}.yaml"
        - os_defaults.yaml
      paths:
        - "vars"
  when: not os_vars_loaded | default(false)
