#SPDX-License-Identifier: MIT-0
---
# tasks file for sudo
- name: Load sudo compatibility aliases
  ansible.builtin.import_tasks: compatibility.yml

- name: Load system-specific variables
  ansible.builtin.import_tasks: load_system_vars.yml
- name: Ensure user '{{ privileged_user }}' exists and has privileged access
  ansible.builtin.import_tasks: add_privileged.yml
