---
- name: Register if sudoers.d directory exists
  ansible.builtin.stat:
    path: /etc/sudoers.d/
  register: sudoers_d

- name: Manage passwordless privilege
  become: true
  ansible.builtin.lineinfile:
    # If sudoers.d exists, use it; otherwise, use /etc/sudoers
    path: "/etc/sudoers{% if sudoers_d.stat.exists %}.d/{{ privileged_user }}{% endif %}"
    create: "{{ 'yes' if sudoers_d.stat.exists else default(omit) }}"
    mode: "{{ '0440' if sudoers_d.stat.exists else default(omit) }}"
    regexp: "^{{ privileged_user }}"
    state: "{{ state | default('absent') }}" # Default to least privilege if not specified
    line: "{{ privileged_user }} ALL=(ALL) NOPASSWD:ALL"
    validate: "/usr/sbin/visudo -cf %s"
