---
# Remove privileged access for user '{{ privileged_user }}'
- name: Remove user from sudo group
  ansible.builtin.include_tasks: remove_user_from_group.yml
  vars:
    group: "{{ privilege_group }}"

- name: Remove passwordless privilege
  ansible.builtin.import_tasks: passwordless_privilege.yml
  vars:
    state: absent

- name: Ensure user '{{ privileged_user }}' does not exist
  ansible.builtin.import_tasks: remove_user.yml
  when: not preserve_user | default(true)
