- name: Ensure QEMU Guest Agent is installed
  become: true
  ansible.builtin.package:
    name: qemu-guest-agent
    state: present

- name: Ensure QEMU Guest Agent is running
  ansible.builtin.systemd_service:
    name: qemu-guest-agent
    state: started
